version: '3.1'
services:
    db:
        image: postgres
        container_name: project_db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - ${DB_PORT}:${DB_PORT}
    nestapp:
        container_name: nestapp
        build:
            context: .
            dockerfile: Dockerfile
        restart: 'on-failure'
        ports:
            - '8082:8082'
        env_file:
            - .env
